# -----------------------------------------------------------------------------
# Copyright Siemens AG, 2016. Part of the SW360 Portal Project.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved. This file is offered as-is,
# without any warranty.
#
# initial author: maximilian.huber@tngtech.com
# -----------------------------------------------------------------------------

sudo: required
dist: trusty
language: java
jdk: openjdk8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y couchdb
  - sudo ./scripts/install-thrift.sh
script: mvn install
